### ISSUE TITLE
Adding buddy.core.crypto namespace

### ISSUE THREAD

**Issue by namig-tahmazli** [babashka/pod-babashka-buddy#7]
I needed to use Cipher algorithms but seems it is not yet supported.
Seems like I can use openssl shrough babashka.process/sh but it would be great if you 
support buddy.core.crypto.

Thank you in advance.

**Comment by borkdude** [comment]
@namig-tahmazli We could add this. Not sure how stateful this API is. Are you interested in doing a PR? Or maybe @brandonstubbs?

**Comment by namig-tahmazli** [comment]
@borkdude Thank you for your instant reply. I am new to Clojure but sure I can give it a try.

**Comment by borkdude** [comment]
@namig-tahmazli I don't want to underestimate your abilities, but in general, for a new Clojure developer it might be non-trivial, given that the API might be stateful. So please give it a try, but don't waste too much energy on it when you're stuck. Feel free to report her with any questions or blocking issues.

**Comment by brandonstubbs** [comment]
Happy to help or do a PR for this. @namig-tahmazli let me know if you are going ahead to give it an attempt first

**Comment by namig-tahmazli** [comment]
> Happy to help or do a PR for this. @namig-tahmazli let me know if you are going ahead to give it an attempt first

@brandonstubbs Thank you for helping.
In this case I think it is better you create PR. 
I would like to check your PR to see how it can be done.

**Comment by namig-tahmazli** [comment]
@borkdude @brandonstubbs I actually create a [PR](https://github.com/babashka/pod-babashka-buddy/pull/8#issue-1475286911) for this.
I did not know how to test whether it was working fine. Also, I am not sure whether my implementation
is enough.

**Comment by brandonstubbs** [comment]
@namig-tahmazli I am on a short holiday at the moment, I can help Friday/Saturday this week when I am back to a computer

**Comment by borkdude** [comment]
Fixed by #10
